# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# Script to assemble methylation  table for Daniel -----
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


# ++++++++++++++++++++
# Dataframes and Lists
# ++++++++++++++++++++

# biospecimen_cl$sample:
#    dataframe with all metadata taken from GDC
# biospecimen_cl:
#    list of dataframes regariding biospecimens
# clinical:
#    list of tabs regarding clinical data
# icgc:
#    dataframe with metadata of the 40 sample of wgs from ICGC
# wgs_specimens :
#   specimen ids of the 40 wgs samples
# metadata:
#    dataframe of metadata from Biolink/ GCD legacy
# tab_dan /tab_dan_no_ben:
#   reshaped and cleaned dataframe for Daniel Biolink/ GCD legacy with or without benign (ben)
#   samples. the replicates were removed
# tab_dan_wgs
#   methilation table for Daniel with WGS information updated
# tab_dan_wgs_rna
#   methilation table for Daniel with RNA information updated
# wgs_table_us
#   WGS table for Daniel


# @@@@@@@@@@@@@@@@@@@@@@@@
# Load TCGA Metadata -----
# @@@@@@@@@@@@@@@@@@@@@@@@
# load obj generated by here("code", "get_metadata_tcga.R")
library(here)
source(here('code', "libraries.R"))

load(file = here("objs", "annotations_methylation.RDA"))

sum(apply(biospecimen_cl$sample, 1, function(x) all(is.na(x))))



# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# Biolink get metadata methylation  -----
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# This is to get metadata of the methylation samples
# getGDCprojects()$project_id
#
# query <- GDCquery(project = "TCGA-PRAD",
#          data.category = "Raw microarray data",
#          data.type = "Raw intensities",
#          experimental.strategy = "Methylation array",
#          legacy = TRUE,
#          file.type = ".idat",
#          platform = "Illumina Human Methylation 450")
#
#
# metadata <- getResults(query)
# save(metadata, file = here("data", "methylation", "metadata.RDA"))

load(file = here("data", "methylation", "metadata.RDA"))



# @@@@@@@@@
# WGS -----
# @@@@@@@@@

# Identify WGS donors and WGS specimens
# the identifier were taken from and a list is also in here("data", "dna_whole", "ICGC_donors.csv")
# https://dcc.icgc.org/repositories?filters=%7B%22file%22:%7B%22projectCode%22:%7B%22is%22:%5B%22PRAD-US%22%5D%7D,%22primarySite%22:%7B%22is%22:%5B%22Prostate%22%5D%7D,%22study%22:%7B%22is%22:%5B%22PCAWG%22%5D%7D,%22experimentalStrategy%22:%7B%22is%22:%5B%22WGS%22%5D%7D,%22fileFormat%22:%7B%22is%22:%5B%22BAM%22%5D%7D%7D%7D&files=%7B%22from%22:1,%22size%22:25%7D

wgs_donors <- list(
  "TCGA-CH-5763",
  "TCGA-EJ-5506",
  "TCGA-HI-7169",
  "TCGA-CH-5788",
  "TCGA-EJ-5503",

  "TCGA-HC-8258",
  "TCGA-HC-7233",
  "TCGA-G9-6336",
  "TCGA-HC-7079",
  "TCGA-EJ-7791",

  "TCGA-HC-7737",
  "TCGA-CH-5771",
  "TCGA-G9-7522",
  "TCGA-CH-5789",
  "TCGA-HC-7744",

  "TCGA-G9-6370",
  "TCGA-G9-6365",
  "TCGA-HC-7740",
  "TCGA-HC-7075",
  "TCGA-CH-5750"
)

wgs_controls <- list(
  "TCGA-CH-5763-11A",
  "TCGA-EJ-5506-10A",
  "TCGA-HI-7169-10A",
  "TCGA-CH-5788-10A",
  "TCGA-EJ-5503-10A",

  "TCGA-HC-8258-10A",
  "TCGA-HC-7233-10A",
  "TCGA-G9-6336-10A",
  "TCGA-HC-7079-10A",
  "TCGA-EJ-7791-10A",

  "TCGA-HC-7737-11A",
  "TCGA-CH-5771-11A",
  "TCGA-G9-7522-10A",
  "TCGA-CH-5789-10A",
  "TCGA-HC-7744-10A",

  "TCGA-G9-6370-10A",
  "TCGA-G9-6365-10A",
  "TCGA-HC-7740-10A",
  "TCGA-HC-7075-10A",
  "TCGA-CH-5750-10A"
)


names(clinical$clinical)

donor_id_tcga_id <- wgs_files %>%
  select(tcga_sample_id , ICGC.Donor) %>%
  mutate(case_submitter_id = sub("-.{3}$", "", tcga_sample_id))

clinical$clinical %>%
  filter(case_submitter_id %in% wgs_donors) %>%
  # select(case_submitter_id, race) %>%
  inner_join(donor_id_tcga_id) %>%
  distinct(case_submitter_id, .keep_all = TRUE) %>%
  filter(race == "black or african american" )


#  tcga_id      icgc_id mutations     genes
# TCGA-HC-8258 DO49815      29         40
# TCGA-HC-7737 DO36285      35         55




